-- 设备事业群商机字段改造 SQL 草案
-- 日期：2026-05-24
-- 适用：当前 H2 / 后续可迁移到 MySQL。生产环境执行前需按实际数据库方言调整。

ALTER TABLE opportunities ADD COLUMN submit_date VARCHAR(20);
ALTER TABLE opportunities ADD COLUMN submitter VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN gov_market_manager VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN submitter_region VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN industry VARCHAR(100);
ALTER TABLE opportunities ALTER COLUMN company VARCHAR(5000);
ALTER TABLE opportunities ALTER COLUMN name VARCHAR(1000);
ALTER TABLE opportunities ADD COLUMN supplier_company VARCHAR(2000);
ALTER TABLE opportunities ADD COLUMN device_types VARCHAR(1000);
ALTER TABLE opportunities ADD COLUMN device_models VARCHAR(1000);
ALTER TABLE opportunities ADD COLUMN demand_quantity INT;
ALTER TABLE opportunities ADD COLUMN estimated_purchase_amount_wan DOUBLE;
ALTER TABLE opportunities ADD COLUMN can_prepare_params BOOLEAN;
ALTER TABLE opportunities ADD COLUMN win_rate_label VARCHAR(50);
ALTER TABLE opportunities ADD COLUMN supply_region VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN requires_exclusive_authorization BOOLEAN;
ALTER TABLE opportunities ADD COLUMN authorized_categories VARCHAR(1000);
ALTER TABLE opportunities ADD COLUMN expected_delivery_date VARCHAR(20);
ALTER TABLE opportunities ADD COLUMN bid_deadline VARCHAR(20);
ALTER TABLE opportunities ADD COLUMN bid_won BOOLEAN;
ALTER TABLE opportunities ADD COLUMN purchase_type VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN winning_amount_wan DOUBLE;
ALTER TABLE opportunities ADD COLUMN deli_bg_delivery_amount_wan DOUBLE;
ALTER TABLE opportunities ADD COLUMN sales_department VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN reported_successfully BOOLEAN;
ALTER TABLE opportunities ADD COLUMN sales VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN creator VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN creator_user_id VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN creator_name VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN submitter_user_id VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN submitter_name VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN owner_user_id VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN owner_name VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN visibility_status VARCHAR(30) DEFAULT 'UNASSIGNED';
ALTER TABLE opportunities ADD COLUMN remind_edit_date VARCHAR(20);
ALTER TABLE opportunities ADD COLUMN last_edit_date VARCHAR(20);
ALTER TABLE opportunities ADD COLUMN province_general_manager VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN a4_business_manager VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN a3_business_manager VARCHAR(100);
ALTER TABLE opportunities ADD COLUMN weekly_progress VARCHAR(3000);
ALTER TABLE opportunities ADD COLUMN legacy_extra_json VARCHAR(3000);

-- 建议索引。H2 支持普通索引；MySQL 可直接复用。
CREATE INDEX IF NOT EXISTS idx_opportunities_industry ON opportunities(industry);
CREATE INDEX IF NOT EXISTS idx_opportunities_submitter_region ON opportunities(submitter_region);
CREATE INDEX IF NOT EXISTS idx_opportunities_supply_region ON opportunities(supply_region);
CREATE INDEX IF NOT EXISTS idx_opportunities_purchase_type ON opportunities(purchase_type);
CREATE INDEX IF NOT EXISTS idx_opportunities_win_rate_label ON opportunities(win_rate_label);
CREATE INDEX IF NOT EXISTS idx_opportunities_bid_won ON opportunities(bid_won);
CREATE INDEX IF NOT EXISTS idx_opportunities_reported_successfully ON opportunities(reported_successfully);
CREATE INDEX IF NOT EXISTS idx_opportunities_creator_user_id ON opportunities(creator_user_id);
CREATE INDEX IF NOT EXISTS idx_opportunities_submitter_user_id ON opportunities(submitter_user_id);
CREATE INDEX IF NOT EXISTS idx_opportunities_owner_user_id ON opportunities(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_opportunities_visibility_status ON opportunities(visibility_status);

-- 企业微信用户目录。第一期可由沙箱数据初始化，后续由企业微信 API 自动同步。
CREATE TABLE IF NOT EXISTS system_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wecom_user_id VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    mobile VARCHAR(50),
    email VARCHAR(200),
    department_id VARCHAR(100),
    department_name VARCHAR(200),
    position VARCHAR(200),
    role VARCHAR(30) DEFAULT 'USER',
    can_view_all BOOLEAN DEFAULT FALSE,
    enabled BOOLEAN DEFAULT TRUE,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    admin_source VARCHAR(30),
    last_synced_at VARCHAR(30),
    created_at VARCHAR(30),
    updated_at VARCHAR(30)
);

CREATE INDEX IF NOT EXISTS idx_system_users_department_id ON system_users(department_id);
CREATE INDEX IF NOT EXISTS idx_system_users_role ON system_users(role);
CREATE INDEX IF NOT EXISTS idx_system_users_enabled ON system_users(enabled);

-- 用户白名单。第一期查看和编辑范围一致，仅管理员可维护。
CREATE TABLE IF NOT EXISTS user_visibility_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_user_id VARCHAR(100) NOT NULL,
    visible_user_id VARCHAR(100) NOT NULL,
    can_view BOOLEAN DEFAULT TRUE,
    can_edit BOOLEAN DEFAULT TRUE,
    created_by_user_id VARCHAR(100),
    created_by_name VARCHAR(100),
    created_at VARCHAR(30),
    updated_at VARCHAR(30)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_visibility_rule
    ON user_visibility_rules(viewer_user_id, visible_user_id);
CREATE INDEX IF NOT EXISTS idx_user_visibility_viewer ON user_visibility_rules(viewer_user_id);
CREATE INDEX IF NOT EXISTS idx_user_visibility_visible ON user_visibility_rules(visible_user_id);

-- 字段级修订记录。普通用户、领导、管理员按商机权限查看。
CREATE TABLE IF NOT EXISTS opportunity_change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id BIGINT NOT NULL,
    editor_user_id VARCHAR(100),
    editor_name VARCHAR(100),
    edited_at VARCHAR(30),
    field_name VARCHAR(100),
    field_label VARCHAR(200),
    old_value VARCHAR(3000),
    new_value VARCHAR(3000),
    source VARCHAR(30),
    permission_source VARCHAR(30),
    owner_user_id VARCHAR(100),
    FOREIGN KEY (opportunity_id) REFERENCES opportunities(id)
);

CREATE INDEX IF NOT EXISTS idx_opp_change_logs_opp_id ON opportunity_change_logs(opportunity_id);
CREATE INDEX IF NOT EXISTS idx_opp_change_logs_editor ON opportunity_change_logs(editor_user_id);
CREATE INDEX IF NOT EXISTS idx_opp_change_logs_edited_at ON opportunity_change_logs(edited_at);

-- 历史数据兼容建议：
-- 1. company 已有值时视为采购单位。
-- 2. name 已有值时视为项目名称。
-- 3. owner 已有值时可同步到 sales，但执行前需确认是否符合业务语义。
-- UPDATE opportunities SET sales = owner WHERE sales IS NULL AND owner IS NOT NULL;
-- 4. value 当前单位为元；不要直接回填 estimated_purchase_amount_wan，需先确认历史金额单位。
-- 5. 历史 Excel 导入数据第一期没有企业微信 wecomUserId，默认 visibility_status = 'UNASSIGNED'，仅管理员可见。
-- 6. 后续可通过用户板块人工归属或姓名映射，补齐 creator_user_id / submitter_user_id / owner_user_id。
